# Generated by Django 5.2.9 on 2025-12-28 12:38

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('module', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='jobcard',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='advisor',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='status',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='technician',
        ),
        migrations.RemoveField(
            model_name='part',
            name='price',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='branch_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='utilization',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='customer',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(default='Individual', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='gst_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='actual_delivery',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='actual_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='complaint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='customer_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='customer_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='estimated_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='fuel_level_in',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='fuel_level_out',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='goodwill_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='is_amc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='is_goodwill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='is_insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='is_warranty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='job_card_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='job_type',
            field=models.CharField(default='General Service', max_length=50),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='labor_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='lead_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='odometer_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='odometer_out',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='parts_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='priority',
            field=models.CharField(default='Normal', max_length=20),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='promised_delivery',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='service_advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='service_tracking_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='workflow_stage',
            field=models.CharField(choices=[('APPOINTMENT', 'Appointment'), ('CHECK_IN', 'Check-in'), ('INSPECTION', 'Digital Inspection'), ('JOB_CARD', 'Job Card Created'), ('ESTIMATE', 'Estimate Prepared'), ('APPROVAL', 'Customer Approval'), ('EXECUTION', 'Task Execution'), ('QC', 'Quality Check'), ('BILLING', 'Billing'), ('DELIVERY', 'Delivery'), ('COMPLETED', 'Service Completed')], default='APPOINTMENT', max_length=20),
        ),
        migrations.AddField(
            model_name='part',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='part',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='part',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='part',
            name='is_oem',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='part',
            name='last_purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='max_stock',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='part',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='part_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='part',
            name='reorder_quantity',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='part',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='part',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='part',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=18, max_digits=5),
        ),
        migrations.AddField(
            model_name='part',
            name='unit',
            field=models.CharField(default='Nos', max_length=50),
        ),
        migrations.AddField(
            model_name='part',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='certifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='actual_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='checklist',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='checklist_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='task',
            name='evidence_photos',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='evidence_videos',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='is_rework',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='labor_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='task',
            name='original_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rework_tasks', to='api.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='pause_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(default='Normal', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='qc_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='qc_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='qc_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='qc_passed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='rework_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='technician_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='total_pause_duration',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='amc_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_odometer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='puc_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='variant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('CAR', 'Car'), ('BIKE', 'Bike'), ('TRUCK', 'Truck'), ('BUS', 'Bus'), ('OTHER', 'Other')], default='CAR', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='warranty_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='actual_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='estimated_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('CEO_OWNER', 'CEO / Owner'), ('REGIONAL_MANAGER', 'Regional Manager'), ('BRANCH_MANAGER', 'Branch Manager'), ('SERVICE_ADVISOR', 'Service Advisor'), ('SALES_EXECUTIVE', 'Sales Executive'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('ACCOUNTS_OFFICER', 'Accounts Officer'), ('HR_MANAGER', 'HR Manager'), ('TECHNICIAN', 'Technician / Mechanic'), ('CRM_EXECUTIVE', 'CRM Executive'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('QC_PASSED', 'QC Passed'), ('QC_FAILED', 'QC Failed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='event_type',
            field=models.CharField(choices=[('WORKFLOW_TRANSITION', 'Workflow Transition'), ('STATUS_CHANGE', 'Status Change'), ('TASK_LOG', 'Task Log'), ('ESTIMATE_CREATED', 'Estimate Created'), ('ESTIMATE_APPROVED', 'Estimate Approved'), ('ESTIMATE_REJECTED', 'Estimate Rejected'), ('PART_ISSUED', 'Part Issued'), ('PART_RETURNED', 'Part Returned'), ('QC_PASSED', 'QC Passed'), ('QC_FAILED', 'QC Failed'), ('PAYMENT_RECEIVED', 'Payment Received'), ('INVOICE_GENERATED', 'Invoice Generated'), ('COMMUNICATION', 'Communication'), ('APPROVAL', 'Approval'), ('SYSTEM', 'System'), ('AI_INSIGHT', 'AI Insight')], max_length=30),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='job_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_timeline', to='api.jobcard'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='role',
            field=models.CharField(blank=True, choices=[('SUPER_ADMIN', 'Super Admin'), ('CEO_OWNER', 'CEO / Owner'), ('REGIONAL_MANAGER', 'Regional Manager'), ('BRANCH_MANAGER', 'Branch Manager'), ('SERVICE_ADVISOR', 'Service Advisor'), ('SALES_EXECUTIVE', 'Sales Executive'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('ACCOUNTS_OFFICER', 'Accounts Officer'), ('HR_MANAGER', 'HR Manager'), ('TECHNICIAN', 'Technician / Mechanic'), ('CRM_EXECUTIVE', 'CRM Executive'), ('CUSTOMER', 'Customer')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Bay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bay_number', models.CharField(max_length=20)),
                ('bay_type', models.CharField(max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('current_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bay', to='api.jobcard')),
            ],
        ),
        migrations.AddField(
            model_name='jobcard',
            name='bay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='api.bay'),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_headquarters', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('parent_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_branches', to='api.branch')),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.AddField(
            model_name='bay',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bays', to='api.branch'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(blank=True, max_length=30)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('OVERRIDE', 'Override')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=100)),
                ('object_repr', models.CharField(max_length=500)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.branch')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='api.branch'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_cards', to='api.branch'),
        ),
        migrations.AddField(
            model_name='part',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='api.branch'),
        ),
        migrations.AddField(
            model_name='profile',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='api.branch'),
        ),
        migrations.CreateModel(
            name='DigitalInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('checklist_data', models.JSONField(default=dict)),
                ('findings', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('photos', models.JSONField(default=list)),
                ('videos', models.JSONField(default=list)),
                ('is_completed', models.BooleanField(default=False)),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('job_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='api.jobcard')),
            ],
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('estimate_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('labor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('parts_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION_REQUESTED', 'Revision Requested')], default='PENDING', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('approval_comment', models.TextField(blank=True, null=True)),
                ('customer_signature', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_estimates', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_estimates', to=settings.AUTH_USER_MODEL)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='api.jobcard')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='EstimateLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('LABOR', 'Labor'), ('PART', 'Part'), ('CONSUMABLE', 'Consumable'), ('MISC', 'Miscellaneous')], max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_approved', models.BooleanField(default=False)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='api.estimate')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.part')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('labor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('parts_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('consumables_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(default='Pending', max_length=20)),
                ('invoice_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='api.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='api.customer')),
                ('job_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='api.jobcard')),
            ],
        ),
        migrations.CreateModel(
            name='PartIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('issued_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('return_quantity', models.IntegerField(default=0)),
                ('return_reason', models.TextField(blank=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_parts', to=settings.AUTH_USER_MODEL)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_issues', to='api.jobcard')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.part')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_issues', to='api.task')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('UPI', 'UPI'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('CREDIT', 'Credit')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.invoice')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('CEO_OWNER', 'CEO / Owner'), ('REGIONAL_MANAGER', 'Regional Manager'), ('BRANCH_MANAGER', 'Branch Manager'), ('SERVICE_ADVISOR', 'Service Advisor'), ('SALES_EXECUTIVE', 'Sales Executive'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('ACCOUNTS_OFFICER', 'Accounts Officer'), ('HR_MANAGER', 'HR Manager'), ('TECHNICIAN', 'Technician / Mechanic'), ('CRM_EXECUTIVE', 'CRM Executive'), ('CUSTOMER', 'Customer')], max_length=30)),
                ('can_create', models.BooleanField(default=False)),
                ('can_read', models.BooleanField(default=True)),
                ('can_update', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.permission')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('WORKFLOW_TRANSITION', 'Workflow Transition'), ('STATUS_CHANGE', 'Status Change'), ('TASK_LOG', 'Task Log'), ('ESTIMATE_CREATED', 'Estimate Created'), ('ESTIMATE_APPROVED', 'Estimate Approved'), ('ESTIMATE_REJECTED', 'Estimate Rejected'), ('PART_ISSUED', 'Part Issued'), ('PART_RETURNED', 'Part Returned'), ('QC_PASSED', 'QC Passed'), ('QC_FAILED', 'QC Failed'), ('PAYMENT_RECEIVED', 'Payment Received'), ('INVOICE_GENERATED', 'Invoice Generated'), ('COMMUNICATION', 'Communication'), ('APPROVAL', 'Approval'), ('SYSTEM', 'System'), ('AI_INSIGHT', 'AI Insight')], max_length=30)),
                ('actor_role', models.CharField(blank=True, choices=[('SUPER_ADMIN', 'Super Admin'), ('CEO_OWNER', 'CEO / Owner'), ('REGIONAL_MANAGER', 'Regional Manager'), ('BRANCH_MANAGER', 'Branch Manager'), ('SERVICE_ADVISOR', 'Service Advisor'), ('SALES_EXECUTIVE', 'Sales Executive'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('ACCOUNTS_OFFICER', 'Accounts Officer'), ('HR_MANAGER', 'HR Manager'), ('TECHNICIAN', 'Technician / Mechanic'), ('CRM_EXECUTIVE', 'CRM Executive'), ('CUSTOMER', 'Customer')], max_length=30, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('evidence', models.JSONField(default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_immutable', models.BooleanField(default=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='api.jobcard')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_jobs_completed', models.IntegerField(default=0)),
                ('total_productive_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_idle_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rework_count', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='api.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='TaskPart',
        ),
        migrations.AlterUniqueTogether(
            name='bay',
            unique_together={('branch', 'bay_number')},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name', 'object_id'], name='api_auditlo_model_n_a07f72_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='api_auditlo_user_id_8f69e8_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'timestamp'], name='api_auditlo_action_070bba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='estimate',
            unique_together={('job_card', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AddIndex(
            model_name='serviceevent',
            index=models.Index(fields=['job_card', 'event_type'], name='api_service_job_car_5dc29a_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceevent',
            index=models.Index(fields=['timestamp'], name='api_service_timesta_6ab8e1_idx'),
        ),
    ]
