# Generated by Django 5.2.9 on 2025-12-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_integrationconfig_license_paymentintent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Admin'), ('CEO_OWNER', 'CEO / Owner'), ('REGIONAL_MANAGER', 'Regional Manager'), ('BRANCH_MANAGER', 'Branch Manager'), ('SERVICE_MANAGER', 'Service Manager'), ('SALES_MANAGER', 'Sales Manager'), ('ACCOUNTS_MANAGER', 'Accounts Manager'), ('SUPERVISOR', 'Supervisor'), ('SERVICE_ADVISOR', 'Service Advisor'), ('SERVICE_ENGINEER', 'Service Engineer'), ('SALES_EXECUTIVE', 'Sales Executive'), ('ACCOUNTANT', 'Accountant'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('HR_MANAGER', 'HR Manager'), ('TECHNICIAN', 'Technician / Mechanic'), ('CRM_EXECUTIVE', 'CRM Executive'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=30),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Admin'), ('CEO_OWNER', 'CEO / Owner'), ('REGIONAL_MANAGER', 'Regional Manager'), ('BRANCH_MANAGER', 'Branch Manager'), ('SERVICE_MANAGER', 'Service Manager'), ('SALES_MANAGER', 'Sales Manager'), ('ACCOUNTS_MANAGER', 'Accounts Manager'), ('SUPERVISOR', 'Supervisor'), ('SERVICE_ADVISOR', 'Service Advisor'), ('SERVICE_ENGINEER', 'Service Engineer'), ('SALES_EXECUTIVE', 'Sales Executive'), ('ACCOUNTANT', 'Accountant'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('HR_MANAGER', 'HR Manager'), ('TECHNICIAN', 'Technician / Mechanic'), ('CRM_EXECUTIVE', 'CRM Executive'), ('CUSTOMER', 'Customer')], max_length=30),
        ),
        migrations.AlterField(
            model_name='serviceevent',
            name='actor_role',
            field=models.CharField(blank=True, choices=[('SUPER_ADMIN', 'Admin'), ('CEO_OWNER', 'CEO / Owner'), ('REGIONAL_MANAGER', 'Regional Manager'), ('BRANCH_MANAGER', 'Branch Manager'), ('SERVICE_MANAGER', 'Service Manager'), ('SALES_MANAGER', 'Sales Manager'), ('ACCOUNTS_MANAGER', 'Accounts Manager'), ('SUPERVISOR', 'Supervisor'), ('SERVICE_ADVISOR', 'Service Advisor'), ('SERVICE_ENGINEER', 'Service Engineer'), ('SALES_EXECUTIVE', 'Sales Executive'), ('ACCOUNTANT', 'Accountant'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('HR_MANAGER', 'HR Manager'), ('TECHNICIAN', 'Technician / Mechanic'), ('CRM_EXECUTIVE', 'CRM Executive'), ('CUSTOMER', 'Customer')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='role',
            field=models.CharField(blank=True, choices=[('SUPER_ADMIN', 'Admin'), ('CEO_OWNER', 'CEO / Owner'), ('REGIONAL_MANAGER', 'Regional Manager'), ('BRANCH_MANAGER', 'Branch Manager'), ('SERVICE_MANAGER', 'Service Manager'), ('SALES_MANAGER', 'Sales Manager'), ('ACCOUNTS_MANAGER', 'Accounts Manager'), ('SUPERVISOR', 'Supervisor'), ('SERVICE_ADVISOR', 'Service Advisor'), ('SERVICE_ENGINEER', 'Service Engineer'), ('SALES_EXECUTIVE', 'Sales Executive'), ('ACCOUNTANT', 'Accountant'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('HR_MANAGER', 'HR Manager'), ('TECHNICIAN', 'Technician / Mechanic'), ('CRM_EXECUTIVE', 'CRM Executive'), ('CUSTOMER', 'Customer')], max_length=30, null=True),
        ),
    ]
