# Generated by Django 5.2.9 on 2025-12-29 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_new_user_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='contract',
            name='coverage_amount',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='premium',
        ),
        migrations.AddField(
            model_name='contract',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='auto_renewal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='billing_model',
            field=models.CharField(choices=[('ONE_TIME', 'One-Time Payment'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('HALF_YEARLY', 'Half-Yearly'), ('ANNUAL', 'Annual')], default='ONE_TIME', max_length=20),
        ),
        migrations.AddField(
            model_name='contract',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='api.branch'),
        ),
        migrations.AddField(
            model_name='contract',
            name='consumables_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='contract',
            name='coverage_hours_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='coverage_km_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='coverage_period_months',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='contract',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='contract',
            name='grace_period_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='contract',
            name='hours_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contract',
            name='km_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contract',
            name='labor_coverage_percent',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AddField(
            model_name='contract',
            name='parts_coverage',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='contract',
            name='penalty_clause',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='priority_handling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='renewal_reminder_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='contract',
            name='resolution_time_hours',
            field=models.IntegerField(default=72),
        ),
        migrations.AddField(
            model_name='contract',
            name='response_time_hours',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated')], default='DRAFT', max_length=30),
        ),
        migrations.AddField(
            model_name='contract',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='suspension_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=18, max_digits=5),
        ),
        migrations.AddField(
            model_name='contract',
            name='terminated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='termination_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('WARRANTY', 'Warranty'), ('EXTENDED_WARRANTY', 'Extended Warranty'), ('AMC', 'Annual Maintenance Contract'), ('SERVICE_PACKAGE', 'Service Package'), ('INSURANCE', 'Insurance'), ('FLEET', 'Fleet Service Contract'), ('SUBSCRIPTION', 'Subscription Plan'), ('CORPORATE', 'Corporate Contract'), ('OEM_DEALER', 'OEM/Dealer Agreement'), ('CUSTOM', 'Custom Contract')], max_length=30),
        ),
        migrations.AlterField(
            model_name='contract',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='api.vehicle'),
        ),
        migrations.CreateModel(
            name='ContractAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('ACTIVATED', 'Activated'), ('SUSPENDED', 'Suspended'), ('RESUMED', 'Resumed'), ('TERMINATED', 'Terminated'), ('RENEWED', 'Renewed'), ('UPGRADED', 'Upgraded'), ('SERVICE_CONSUMED', 'Service Consumed'), ('GOODWILL_APPLIED', 'Goodwill Applied')], max_length=30)),
                ('old_values', models.JSONField(default=dict)),
                ('new_values', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='api.contract')),
                ('job_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.jobcard')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('service_type', models.CharField(max_length=100)),
                ('parts_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('labor_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('covered_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customer_payable', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('km_at_service', models.IntegerField(blank=True, null=True)),
                ('hours_at_service', models.IntegerField(blank=True, null=True)),
                ('sla_met', models.BooleanField(default=True)),
                ('response_time_actual', models.IntegerField(blank=True, null=True)),
                ('resolution_time_actual', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='api.contract')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_consumptions', to='api.invoice')),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_consumptions', to='api.jobcard')),
            ],
            options={
                'ordering': ['-service_date'],
            },
        ),
        migrations.CreateModel(
            name='ContractApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_level', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_approvals', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='api.contract')),
            ],
            options={
                'ordering': ['approval_level', '-created_at'],
                'unique_together': {('contract', 'approver', 'approval_level')},
            },
        ),
        migrations.CreateModel(
            name='ContractCoverageRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100)),
                ('is_covered', models.BooleanField(default=True)),
                ('coverage_percent', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('visit_limit', models.IntegerField(blank=True, null=True)),
                ('visits_used', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_rules', to='api.contract')),
            ],
            options={
                'unique_together': {('contract', 'service_type')},
            },
        ),
        migrations.CreateModel(
            name='ContractVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_vehicles', to='api.contract')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_links', to='api.vehicle')),
            ],
            options={
                'unique_together': {('contract', 'vehicle')},
            },
        ),
    ]
