# Generated by Django 5.2.9 on 2026-01-08 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_currency_language_preferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('adjustment_type', models.CharField(choices=[('INCREASE', 'Stock Increase'), ('DECREASE', 'Stock Decrease'), ('SCRAP', 'Scrap'), ('DAMAGE', 'Damage'), ('THEFT', 'Theft/Loss'), ('CORRECTION', 'Correction'), ('OPENING_STOCK', 'Opening Stock')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('stock_before', models.IntegerField(default=0)),
                ('stock_after', models.IntegerField(default=0)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reference_document', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_adjustments', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='api.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_adjustments', to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='api.part')),
            ],
        ),
        migrations.CreateModel(
            name='StockReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('quantity', models.IntegerField(default=1)),
                ('return_reason', models.TextField()),
                ('condition', models.CharField(choices=[('GOOD', 'Good - Restock'), ('DEFECTIVE', 'Defective'), ('DAMAGED', 'Damaged'), ('WRONG_PART', 'Wrong Part')], default='GOOD', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('RESTOCKED', 'Restocked'), ('SCRAPPED', 'Scrapped')], default='PENDING', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_returns', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_returns', to='api.branch')),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_returns', to='api.jobcard')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='api.part')),
                ('part_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='api.partissue')),
                ('returned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_parts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('action', models.CharField(choices=[('ISSUE', 'Part Issued'), ('RETURN', 'Part Returned'), ('RESERVE', 'Part Reserved'), ('RELEASE', 'Reservation Released'), ('GRN', 'Goods Received'), ('TRANSFER_OUT', 'Transfer Out'), ('TRANSFER_IN', 'Transfer In'), ('ADJUSTMENT', 'Stock Adjustment'), ('SCRAP', 'Scrapped')], max_length=30)),
                ('quantity', models.IntegerField()),
                ('stock_before', models.IntegerField()),
                ('stock_after', models.IntegerField()),
                ('reference_type', models.CharField(max_length=30)),
                ('reference_id', models.IntegerField()),
                ('reference_number', models.CharField(max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_immutable', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_audit_logs', to='api.branch')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='api.part')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['part', 'timestamp'], name='api_invento_part_id_484886_idx'), models.Index(fields=['branch', 'timestamp'], name='api_invento_branch__769586_idx'), models.Index(fields=['reference_type', 'reference_id'], name='api_invento_referen_e24f8e_idx')],
            },
        ),
    ]
