# Generated by Django 5.2.9 on 2026-01-08 07:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_stockadjustment_stockreturn_inventoryauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationrule',
            name='business_hours_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notification_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='delay_unit',
            field=models.CharField(choices=[('MINUTES', 'Minutes'), ('HOURS', 'Hours'), ('DAYS', 'Days')], default='MINUTES', max_length=10),
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='delay_value',
            field=models.IntegerField(default=0, help_text='Delay before sending (0 = immediate)'),
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='retry_count',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='retry_interval',
            field=models.IntegerField(default=30, help_text='Retry interval in minutes'),
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='skip_holidays',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='body_html',
            field=models.TextField(blank=True, help_text='HTML content for email notifications'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Default template for event+channel+language'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='subject',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='NotificationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(help_text='NotificationEvent, NotificationTemplate, etc.', max_length=50)),
                ('entity_id', models.IntegerField()),
                ('entity_name', models.CharField(max_length=200)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('ACTIVATE', 'Activate'), ('DEACTIVATE', 'Deactivate'), ('TEST_SEND', 'Test Send')], max_length=20)),
                ('changes', models.JSONField(default=dict, help_text='Before/after values')),
                ('reason', models.TextField(blank=True)),
                ('performed_by_name', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('module', models.CharField(choices=[('SERVICE', 'Service & Workflow'), ('CRM', 'Customer Relations'), ('INVENTORY', 'Inventory & Supplier'), ('ACCOUNTS', 'Accounts & Finance'), ('CONTRACTS', 'Contracts'), ('HR', 'Human Resources'), ('SYSTEM', 'System')], max_length=20)),
                ('trigger_type', models.CharField(choices=[('TIME_BASED', 'Time Based'), ('STATUS_BASED', 'Status Based'), ('SLA_BASED', 'SLA Based'), ('RECURRING', 'Recurring'), ('MANUAL', 'Manual')], default='STATUS_BASED', max_length=20)),
                ('trigger_condition', models.TextField(blank=True, help_text='Description of when this event is triggered')),
                ('available_variables', models.JSONField(default=list, help_text='List of variable names available for this event')),
                ('is_active', models.BooleanField(default=True)),
                ('is_system_event', models.BooleanField(default=False, help_text='System events cannot be deleted')),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notification_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['module', 'display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='api.notificationevent'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='api.notificationevent'),
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('event_code', models.CharField(max_length=50)),
                ('event_name', models.CharField(max_length=200)),
                ('template_name', models.CharField(blank=True, max_length=200)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('PUSH', 'Push Notification'), ('IN_APP', 'In-App Notification')], max_length=20)),
                ('recipient_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('TECHNICIAN', 'Technician'), ('SERVICE_ADVISOR', 'Service Advisor'), ('MANAGER', 'Manager'), ('ACCOUNTS_TEAM', 'Accounts Team'), ('HR_TEAM', 'HR Team'), ('BRANCH_BASED', 'Branch Based'), ('ROLE_BASED', 'Role Based'), ('SPECIFIC_USER', 'Specific User')], max_length=20)),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('content_rendered', models.TextField(help_text='Final rendered message content')),
                ('context_data', models.JSONField(default=dict)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('BOUNCED', 'Bounced'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('external_message_id', models.CharField(blank=True, help_text='ID from SMS/Email provider', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.branch')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='api.notificationevent')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='api.notificationtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('PUSH', 'Push Notification'), ('IN_APP', 'In-App Notification')], max_length=20)),
                ('recipient_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('TECHNICIAN', 'Technician'), ('SERVICE_ADVISOR', 'Service Advisor'), ('MANAGER', 'Manager'), ('ACCOUNTS_TEAM', 'Accounts Team'), ('HR_TEAM', 'HR Team'), ('BRANCH_BASED', 'Branch Based'), ('ROLE_BASED', 'Role Based'), ('SPECIFIC_USER', 'Specific User')], max_length=20)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('context_data', models.JSONField(default=dict, help_text='Variable values for template rendering')),
                ('reference_type', models.CharField(blank=True, help_text='e.g., JobCard, Invoice', max_length=50)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('priority', models.IntegerField(default=5)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('BOUNCED', 'Bounced'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queued_notifications', to='api.notificationevent')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queued_notifications', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.notificationtemplate')),
            ],
            options={
                'ordering': ['priority', 'scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipientRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('recipient_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('TECHNICIAN', 'Technician'), ('SERVICE_ADVISOR', 'Service Advisor'), ('MANAGER', 'Manager'), ('ACCOUNTS_TEAM', 'Accounts Team'), ('HR_TEAM', 'HR Team'), ('BRANCH_BASED', 'Branch Based'), ('ROLE_BASED', 'Role Based'), ('SPECIFIC_USER', 'Specific User')], max_length=20)),
                ('is_primary', models.BooleanField(default=True)),
                ('is_cc', models.BooleanField(default=False)),
                ('specific_roles', models.JSONField(default=list, help_text='List of role codes for ROLE_BASED type')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recipient_rules', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_rules', to='api.notificationevent')),
                ('specific_branches', models.ManyToManyField(blank=True, related_name='notification_recipient_rules', to='api.branch')),
                ('specific_users', models.ManyToManyField(blank=True, related_name='notification_recipient_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event', '-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationEscalationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('escalation_level', models.IntegerField(default=1)),
                ('escalation_after_minutes', models.IntegerField(default=60)),
                ('escalation_condition', models.CharField(choices=[('DELIVERY_FAILED', 'Delivery Failed'), ('NO_RESPONSE', 'No Response'), ('SLA_BREACH', 'SLA Breach'), ('RETRY_EXHAUSTED', 'Retry Exhausted')], default='DELIVERY_FAILED', max_length=50)),
                ('escalate_to_roles', models.JSONField(default=list)),
                ('fallback_channel', models.CharField(blank=True, choices=[('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('PUSH', 'Push Notification'), ('IN_APP', 'In-App Notification')], max_length=20)),
                ('notify_original_recipient', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('escalate_to_users', models.ManyToManyField(blank=True, related_name='escalation_notifications', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_rules', to='api.notificationevent')),
            ],
            options={
                'ordering': ['event', 'escalation_level'],
                'unique_together': {('event', 'escalation_level')},
            },
        ),
        migrations.CreateModel(
            name='NotificationChannelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('PUSH', 'Push Notification'), ('IN_APP', 'In-App Notification')], max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=1, help_text='1=highest priority')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_configs', to='api.notificationtemplate')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_configs', to='api.notificationevent')),
            ],
            options={
                'ordering': ['event', 'priority'],
                'unique_together': {('event', 'channel')},
            },
        ),
    ]
