# Generated by Django 5.2.9 on 2026-02-16 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_notification_center_v2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='cgst_rate',
            field=models.DecimalField(decimal_places=2, default=9, max_digits=5),
        ),
        migrations.AddField(
            model_name='part',
            name='damaged',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='part',
            name='gst_type',
            field=models.CharField(choices=[('INTRA_STATE', 'Intra-State (CGST+SGST)'), ('INTER_STATE', 'Inter-State (IGST)'), ('EXEMPT', 'Exempt')], default='INTRA_STATE', max_length=20),
        ),
        migrations.AddField(
            model_name='part',
            name='igst_rate',
            field=models.DecimalField(decimal_places=2, default=18, max_digits=5),
        ),
        migrations.AddField(
            model_name='part',
            name='in_transit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='part',
            name='is_discontinued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='part',
            name='landing_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Auto-calculated: purchase price + tax + freight', max_digits=12),
        ),
        migrations.AddField(
            model_name='part',
            name='margin_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Auto-calculated margin %', max_digits=5),
        ),
        migrations.AddField(
            model_name='part',
            name='max_discount_percent',
            field=models.DecimalField(decimal_places=2, default=15, help_text='Maximum allowed discount %', max_digits=5),
        ),
        migrations.AddField(
            model_name='part',
            name='min_margin_percent',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Minimum allowed margin %', max_digits=5),
        ),
        migrations.AddField(
            model_name='part',
            name='sgst_rate',
            field=models.DecimalField(decimal_places=2, default=9, max_digits=5),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('QUOTED', 'Quoted'), ('NEGOTIATION', 'Negotiation'), ('CUSTOMER', 'Customer'), ('CONVERTED', 'Converted'), ('LOST', 'Lost')], default='NEW', max_length=20),
        ),
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_VERIFICATION', 'Pending Verification'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('PARTIALLY_PAID', 'Partially Paid'), ('DISPUTED', 'Disputed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=25)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('freight_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tds_applicable', models.BooleanField(default=False)),
                ('tds_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tds_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('supplier_gst_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_supplier_invoices', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_invoices', to='api.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supplier_invoices', to=settings.AUTH_USER_MODEL)),
                ('grn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoices', to='api.goodsreceiptnote')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_invoices', to='api.purchaseorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='api.supplier')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_supplier_invoices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hsn_code', models.CharField(blank=True, max_length=20)),
                ('grn_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='api.grnline')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='api.supplierinvoice')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.part')),
            ],
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('movement_type', models.CharField(choices=[('OPENING', 'Opening Stock'), ('PURCHASE', 'Purchase (GRN)'), ('RESERVE', 'Reserved'), ('RELEASE', 'Released'), ('ISSUE', 'Issued to Job Card'), ('RETURN_JOB', 'Return from Job Card'), ('RETURN_SUPPLIER', 'Return to Supplier'), ('TRANSFER_OUT', 'Transfer Out'), ('TRANSFER_IN', 'Transfer In'), ('ADJUSTMENT_IN', 'Adjustment Increase'), ('ADJUSTMENT_OUT', 'Adjustment Decrease'), ('DAMAGE', 'Damaged'), ('SCRAP', 'Scrapped')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_before', models.IntegerField(default=0)),
                ('stock_after', models.IntegerField(default=0)),
                ('reserved_before', models.IntegerField(default=0)),
                ('reserved_after', models.IntegerField(default=0)),
                ('available_before', models.IntegerField(default=0)),
                ('available_after', models.IntegerField(default=0)),
                ('from_location', models.CharField(blank=True, max_length=100)),
                ('to_location', models.CharField(blank=True, max_length=100)),
                ('reference_type', models.CharField(choices=[('JOB_CARD', 'Job Card'), ('PO', 'Purchase Order'), ('GRN', 'Goods Receipt'), ('TRANSFER', 'Stock Transfer'), ('ADJUSTMENT', 'Stock Adjustment'), ('RETURN', 'Stock Return'), ('RESERVATION', 'Part Reservation'), ('PART_ISSUE', 'Part Issue'), ('SUPPLIER_RETURN', 'Supplier Return'), ('OPENING', 'Opening Balance')], max_length=30)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_immutable', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledger', to='api.branch')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledger', to='api.part')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['part', 'branch', 'timestamp'], name='api_stockle_part_id_a4d8de_idx'), models.Index(fields=['movement_type', 'timestamp'], name='api_stockle_movemen_2511ef_idx'), models.Index(fields=['reference_type', 'reference_id'], name='api_stockle_referen_84fa19_idx')],
            },
        ),
    ]
