# Generated by Django 5.2.9 on 2026-02-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_part_cgst_rate_part_damaged_part_gst_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('QUOTED', 'Quoted'), ('NEGOTIATION', 'Negotiation'), ('CUSTOMER', 'Customer'), ('LOST', 'Lost')], default='NEW', max_length=20),
        ),
    ]
