# Generated by Django 5.2.9 on 2026-04-05 16:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_converted_lead_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('logo_url', models.URLField(blank=True)),
                ('country_of_origin', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HsnSacCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True)),
                ('description', models.TextField()),
                ('gst_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('code_type', models.CharField(choices=[('HSN', 'HSN'), ('SAC', 'SAC')], max_length=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'HSN/SAC Code',
                'verbose_name_plural': 'HSN/SAC Codes',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('UTILITY', 'Utility'), ('MARKETING', 'Marketing'), ('AUTHENTICATION', 'Authentication')], max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('body', models.TextField()),
                ('variables', models.JSONField(default=list)),
                ('meta_template_id', models.CharField(blank=True, max_length=100)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='gstin',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='branch',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='part',
            name='auto_reorder_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='part',
            name='reorder_point',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='failed_login_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=30)),
                ('account_holder_name', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('swift_code', models.CharField(blank=True, max_length=20)),
                ('account_type', models.CharField(choices=[('SAVINGS', 'Savings'), ('CURRENT', 'Current'), ('OVERDRAFT', 'Overdraft')], default='CURRENT', max_length=10)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='api.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='api.department')),
            ],
        ),
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='api.partcategory')),
            ],
            options={
                'verbose_name_plural': 'Part Categories',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=30)),
                ('prefix', models.CharField(max_length=10)),
                ('include_year', models.BooleanField(default=True)),
                ('include_month', models.BooleanField(default=False)),
                ('padding_length', models.PositiveIntegerField(default=5)),
                ('current_sequence', models.PositiveIntegerField(default=0)),
                ('reset_frequency', models.CharField(choices=[('NEVER', 'Never'), ('YEARLY', 'Yearly'), ('MONTHLY', 'Monthly')], default='YEARLY', max_length=10)),
                ('last_reset_date', models.DateField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_sequences', to='api.branch')),
            ],
            options={
                'unique_together': {('document_type', 'branch')},
            },
        ),
    ]
