# Generated by Django 5.2.9 on 2026-04-06 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_brand_hsnsaccode_whatsapptemplate_branch_gstin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='renewal_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewed_from', to='api.contract'),
        ),
        migrations.AddField(
            model_name='part',
            name='part_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='api.brand'),
        ),
        migrations.AddField(
            model_name='part',
            name='part_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='api.partcategory'),
        ),
    ]
